# Generated by Django 4.0.3 on 2022-04-15 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0006_alter_account_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postCode', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
                ('kakaoLatitude', models.CharField(max_length=50)),
                ('kakaoLongitude', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('area', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('deposit', models.IntegerField()),
                ('price', models.IntegerField()),
                ('discussion', models.CharField(max_length=50)),
                ('client', models.PositiveSmallIntegerField(choices=[(1, '건물주'), (2, '가게주')], null=True)),
                ('sort', models.PositiveSmallIntegerField(choices=[(1, '전체'), (2, '월세'), (3, '전세')], null=True)),
                ('count', models.IntegerField()),
                ('range', models.PositiveSmallIntegerField(choices=[(1, '상가, 점포로만 사용하는 게 좋아요'), (2, '상가, 점포와 사무실 둘 다 사용 가능해요')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.address')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.account')),
            ],
            options={
                'db_table': 'board',
            },
        ),
    ]
